version: '3.8'

services:
  # Banco de Dados Principal (SQL Server)
  sqlserver:
    container_name: rss_sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Str0ngP@ssword!
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  # Banco de Cache (Redis)
  redis:
    container_name: rss_redis
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  sqlserver_data:
  redis_data: